require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.6

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 40

Rails/FilePath:
  EnforcedStyle: arguments

  
Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25
